#!/usr/bin/env bash
# Regenerates tests/generated/AllPacketFactories.inc from the kernel
# membership list (tests/arch/kernel_files.txt) — since the 2.4 flip that
# list IS the set of packet sources compiled into de-kernel, the one wire
# archive every server and the tests link.
#
# The .inc is the wire-layout inventory's registry: one include + one
# registration per packet factory whose class is compiled into de-kernel.
# It is committed; tests/ratchet/ratchets.sh fails when it drifts from
# this script's output or when PacketFactoryManager registers a factory
# that is missing from it.
#
# Usage: tests/tools/gen_factory_list.sh   (run from the repository root)
set -euo pipefail

KERNEL_LIST="tests/arch/kernel_files.txt"
OUT="tests/generated/AllPacketFactories.inc"

[ -f "$KERNEL_LIST" ] || { echo "run from the repository root" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"

# Packet .cpp basenames from the kernel membership (skip commented lines,
# skip *Handler.cpp — handlers hold no factory).
bases=$(grep -vE '^\s*#' "$KERNEL_LIST" \
    | grep -oE '(GC|CG|CL|LC|GL|LG|GS|SG|GG|GM)[A-Za-z0-9_]*\.cpp' \
    | sed 's/\.cpp$//' \
    | grep -v 'Handler$' \
    | sort -u)

tmp_inc=$(mktemp)
tmp_reg=$(mktemp)
trap 'rm -f "$tmp_inc" "$tmp_reg"' EXIT

for base in $bases; do
    header="src/Core/${base}.h"
    [ -f "$header" ] || continue
    # A packet header declares its factory as
    #   class <Name>Factory : public PacketFactory
    # or, for a few derived packets, as a subclass of another packet's factory:
    #   class <Name>Factory : public <Other>Factory
    factories=$(grep -oE 'class [A-Za-z0-9_]+Factory *: *public [A-Za-z0-9_]*Factory' "$header" \
        | sed -E 's/class ([A-Za-z0-9_]+Factory).*/\1/' | sort -u || true)
    [ -n "$factories" ] || continue
    echo "#include \"${base}.h\"" >> "$tmp_inc"
    for f in $factories; do
        echo "    factories.push_back(new ${f}());" >> "$tmp_reg"
    done
done

{
    echo "// Generated by tests/tools/gen_factory_list.sh -- DO NOT EDIT BY HAND."
    echo "// Regenerate after changing tests/arch/kernel_files.txt;"
    echo "// tests/ratchet/ratchets.sh pins this file against a fresh generation."
    echo "// clang-format off"
    echo "#ifdef ALL_PACKET_FACTORIES_INCLUDES"
    sort -u "$tmp_inc"
    echo "#endif // ALL_PACKET_FACTORIES_INCLUDES"
    echo "#ifdef ALL_PACKET_FACTORIES_REGISTER"
    sort -u "$tmp_reg"
    echo "#endif // ALL_PACKET_FACTORIES_REGISTER"
    echo "// clang-format on"
} > "$OUT"

echo "wrote $OUT ($(grep -c 'push_back' "$OUT") factories)"
