//////////////////////////////////////////////////////////////////////
//
// Filename    : wire_layout_test.cpp
// Description : Regenerates the wire-layout inventory from every packet
//               factory compiled into TestPackets and compares it to the
//               committed tests/wire-layout.txt — so a packet-ID or
//               max-size change is a reviewable diff in the same commit,
//               never a silent client break (the sidecar
//               WireFieldInventoryTest pattern).
//
//               The factory list is tests/generated/AllPacketFactories.inc,
//               produced by tests/tools/gen_factory_list.sh and pinned by
//               tests/ratchet/ratchets.sh.
//
//////////////////////////////////////////////////////////////////////

#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <sstream>
#include <vector>

#include <gtest/gtest.h>

#include "Packet.h"
#include "PacketFactory.h"
#include "TestStreams.h"

#define ALL_PACKET_FACTORIES_INCLUDES
#include "AllPacketFactories.inc"
#undef ALL_PACKET_FACTORIES_INCLUDES

using wiretest::isRecording;

namespace {

std::vector<PacketFactory*> makeAllFactories() {
    std::vector<PacketFactory*> factories;
#define ALL_PACKET_FACTORIES_REGISTER
#include "AllPacketFactories.inc"
#undef ALL_PACKET_FACTORIES_REGISTER
    return factories;
}

struct InventoryEntry {
    std::string name;
    PacketSize_t maxSize;
};

std::map<PacketID_t, InventoryEntry> buildInventory(const std::vector<PacketFactory*>& factories,
                                                    std::vector<std::string>& idConflicts) {
    std::map<PacketID_t, InventoryEntry> inventory;
    for (size_t i = 0; i < factories.size(); i++) {
        PacketFactory* pFactory = factories[i];
        PacketID_t id = pFactory->getPacketID();
        InventoryEntry entry;
        entry.name = pFactory->getPacketName();
        entry.maxSize = pFactory->getPacketMaxSize();

        std::map<PacketID_t, InventoryEntry>::iterator existing = inventory.find(id);
        if (existing != inventory.end()) {
            if (existing->second.name != entry.name) {
                std::ostringstream conflict;
                conflict << "packet ID " << id << " claimed by both " << existing->second.name << " and " << entry.name;
                idConflicts.push_back(conflict.str());
            }
            continue;
        }
        inventory[id] = entry;
    }
    return inventory;
}

std::string renderInventory(const std::map<PacketID_t, InventoryEntry>& inventory) {
    std::ostringstream out;
    out << "# Wire-layout inventory: packet-id<TAB>name<TAB>max-body-size\n";
    out << "# Generated by wire_layout_test (UPDATE_GOLDENS=1 to re-record).\n";
    out << "# A diff in this file is a wire-protocol change: the client repo's\n";
    out << "# hand-maintained packet copies must ship the identical change.\n";
    for (std::map<PacketID_t, InventoryEntry>::const_iterator it = inventory.begin(); it != inventory.end(); ++it)
        out << it->first << "\t" << it->second.name << "\t" << it->second.maxSize << "\n";
    return out.str();
}

TEST(WireLayoutTest, packetIdsAreUniqueAcrossAllFactories) {
    std::vector<PacketFactory*> factories = makeAllFactories();
    ASSERT_FALSE(factories.empty());
    std::vector<std::string> idConflicts;
    buildInventory(factories, idConflicts);
    for (size_t i = 0; i < idConflicts.size(); i++)
        ADD_FAILURE() << idConflicts[i];
    for (size_t i = 0; i < factories.size(); i++)
        delete factories[i];
}

TEST(WireLayoutTest, inventoryMatchesCommittedFile) {
    std::vector<PacketFactory*> factories = makeAllFactories();
    ASSERT_FALSE(factories.empty());

    std::vector<std::string> idConflicts;
    std::map<PacketID_t, InventoryEntry> inventory = buildInventory(factories, idConflicts);
    const std::string actual = renderInventory(inventory);

    const char* path = WIRETEST_LAYOUT_FILE;
    if (isRecording()) {
        std::ofstream file(path, std::ios::trunc);
        ASSERT_TRUE(file.good()) << "cannot write " << path;
        file << actual;
        std::printf("recorded %s (%d packets)\n", path, (int)inventory.size());
    } else {
        std::ifstream file(path);
        ASSERT_TRUE(file.good()) << "missing " << path << " — run the tests once with UPDATE_GOLDENS=1 to record it";
        std::stringstream expected;
        expected << file.rdbuf();
        EXPECT_EQ(expected.str(), actual)
            << "the wire-layout inventory drifted from " << path
            << " — review the diff as a protocol change and re-record with UPDATE_GOLDENS=1";
    }

    for (size_t i = 0; i < factories.size(); i++)
        delete factories[i];
}

// Every factory must be able to create its packet, and the packet must
// report the same ID as its factory — createPacket/getPacketID mismatches
// would misroute packets at dispatch time.
TEST(WireLayoutTest, everyFactoryCreatesAPacketWithItsOwnId) {
    std::vector<PacketFactory*> factories = makeAllFactories();
    ASSERT_FALSE(factories.empty());
    for (size_t i = 0; i < factories.size(); i++) {
        Packet* pPacket = factories[i]->createPacket();
        ASSERT_TRUE(pPacket != NULL) << factories[i]->getPacketName();
        EXPECT_EQ(factories[i]->getPacketID(), pPacket->getPacketID()) << factories[i]->getPacketName();
        delete pPacket;
    }
    for (size_t i = 0; i < factories.size(); i++)
        delete factories[i];
}

} // namespace
