#
#
# Filename    : excel96-sharedserver.conf
# Written By  : Reiot
#
#--------------------------------------------------------------------------------

#--------------------------------------------------------------------------------
# User Section
#--------------------------------------------------------------------------------

User : excel96
# HomePath : /mnt/c/project/opendarkeden/server
HomePath : /home/darkeden/vs

#--------------------------------------------------------------------------------
# Game - Shared Server Section
#--------------------------------------------------------------------------------
TCPPort : 33063

#--------------------------------------------------
# DB connection
#--------------------------------------------------
DB_HOST : 192.168.111.40
DB_PORT : 33061
DB_DB : DARKEDEN
DB_USER : scott
DB_PASSWORD : tiger

UI_DB_HOST : 192.168.111.40
UI_DB_PORT : 33061
UI_DB_DB : USERINFO
UI_DB_USER : scott
UI_DB_PASSWORD : tiger


#--------------------------------------------------
# World Info
#--------------------------------------------------
Dimension : 1

WorldID : 1
