CREATE DATABASE IF NOT EXISTS DARKEDEN CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS USERINFO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER 'elcastle'@'%' IDENTIFIED BY 'elca110';
GRANT ALL PRIVILEGES ON DARKEDEN.* TO 'elcastle'@'%';
GRANT ALL PRIVILEGES ON USERINFO.* TO 'elcastle'@'%';
