>>> STARTING GAME SERVER...
>>> RANDOMIZATION INITIALIZATION SUCCESS...
>>> COMMAND-LINE PARAMETER READING SUCCESS...
==============================================================================
UNHANDLED EXCEPTION OCCURED
==============================================================================
